import type { MetaTagsProps } from "svelte-meta-tags";

export let seoMetaTags: MetaTagsProps = {
	title: "Svelte Shadcn Blocks - 50+ Marketing UI Components",
	titleTemplate: "%s | Svelte Shadcn Blocks",
	description:
		"Build beautiful websites faster with 50+ ready-to-use marketing UI components built with Svelte, Tailwind CSS, and Shadcn. Perfect for SaaS, startups, portfolios, and landing pages.",
	keywords: [
		"Svelte UI components",
		"Svelte marketing components",
		"Tailwind CSS components",
		"Shadcn Svelte blocks",
		"Svelte landing page UI",
		"Svelte website templates",
		"UI components for Svelte",
		"marketing website blocks",
		"Svelte Tailwind UI kit",
		"free Svelte components",
		"Svelte SaaS templates",
		"Svelte portfolio components",
		"Svelte Tailwind templates",
		"ready-to-use Svelte blocks",
		"Shadcn UI for Svelte",
		"copy-paste Svelte components",
		"Svelte UI builder",
		"Svelte kit landing pages",
		"responsive Svelte components",
		"Svelte frontend templates",
		"modern UI components Svelte",
		"minimal UI blocks Svelte",
		"Svelte blocks for startups",
		"Svelte homepage components",
		"Svelte Tailwind marketing blocks",
		"Svelte design system",
		"UI toolkit for Svelte",
		"Svelte Shadcn kit",
		"Svelte business website blocks",
		"lightweight Svelte UI components",
		"Svelte UI",
		"UI Blocks",
		"Tailwind UI",
		"Svelte Kit",
		"Shadcn Svelte",
		"Landing Blocks",
		"Marketing UI",
		"Svelte Tailwind",
		"Hero Sections",
		"CTA Blocks",
		"Pricing Tables",
		"Feature Cards",
		"SaaS UI",
		"Minimal UI",
		"Clean Design",
		"Dev Templates",
		"Copy Paste UI",
		"UI Library",
		"Frontend Kit",
		"Modern Blocks",
	],
	twitter: {
		cardType: "summary_large_image",
		title: "Svelte Shadcn Blocks - 50+ Marketing UI Components",
		description:
			"Supercharge your Svelte projects with reusable, customizable, and aesthetic marketing components powered by Tailwind CSS and Shadcn.",
		image: "https://sv-blocks.vercel.app/og.png",
		site: "@Sikandar_Bhide",
		creator: "@Sikandar_Bhide",
	},
	openGraph: {
		url: "https://sv-blocks.vercel.app",
		type: "website",
		title: "Svelte Shadcn Blocks - 50+ Marketing UI Components",
		description:
			"A collection of 50+ elegant, responsive, and copy-paste ready UI blocks for marketing websites. Designed with Tailwind CSS and powered by Svelte + Shadcn.",
		siteName: "Svelte Shadcn Blocks",
		images: [
			{
				url: "https://sv-blocks.vercel.app/og.png",
				type: "image/png",
				width: 1200,
				height: 630,
				alt: "Svelte Shadcn Blocks - Preview Image",
			},
		],
	},
};
